### ISSUE TITLE
No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier(panic on andriod9+)

### ISSUE THREAD

**Issue by junjie-bianjie** [bianjieai/opb-sdk-java#40]
**What problem?**
No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier；
![图片](https://user-images.githubusercontent.com/49903386/151116610-1e5354c1-f61d-499d-89b2-84ddb9c029c6.png)

**How to reproduce**
After using the **opbConfig.setRequireTransportSecurity** line of code, AllowAllHostnameVerifier is called at the bottom layer, but in 宜搭 of frame Android 9 and above, this AllowAllHostnameVerifier.class.INSTANCE does not exist, so using it will cause conflicts

**What you want**
I hope to fix this bug

**Comment by cotiAutonomousCar** [comment]
this bug has been fixed, use java  native net frame replace org.apache.http
#41

**Comment by junjie-bianjie** [comment]
fix on v0.1.7 version
