### ISSUE TITLE
error:irita.sdk.exception.IritaSDKException: log: Required roles: [ROOT_ADMIN POWER_USER]; sender roles: []. : unauthorized operation

### ISSUE THREAD

**Issue by tensecond** [bianjieai/opb-sdk-java#47]
1、已在后台创建了一个项目，下载对应参数
2、Demo里面替换了对应助计词、projectId、projectKey
3、调用nftClient.issueDenom(req, baseTx)报错，这个错误怎么回事，需要怎么解决？

**Comment by junjie-bianjie** [comment]
文昌链主网中发issueDenom交易，需要像bsn申请相应的权限，关于权限如何申请可以私信我
wenchain send issueDenom tx, need have a authroity
