### ISSUE TITLE
可以通过sdk创建链账户么

### ISSUE THREAD

**Issue by cookiefinder** [bianjieai/opb-sdk-java#78]

**Comment by junjie-bianjie** [comment]
README.md 中的 Key Manger管理 就是创建链账户，需要注意这里创建的是离线账户。正式使用需要该账户有能量值（比如有人给他转账，有人给他开通代付）

**Comment by junjie-bianjie** [comment]
离线账户在链上是查不到的。想要在链上查到需要有能量值（比如有人给他转账，有人给他开通代付）
